# Generated by Django 2.0.7 on 2020-11-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topics',
            new_name='topic',
        ),
    ]
